### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by SchlauFuchs** [SiskSjet/BuildColors#4]
the readme lacks hints on how to install this plugin.

**Comment by SiskSjet** [comment]
That's true sorry. The easiest way is to download it from [SteamWorkshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1475392343).

You can also download the latest zip from releases [BuildColors.1.1.2.zip
](https://github.com/SiskSjet/BuildColors/releases/download/v1.1.2/BuildColors.1.1.2.zip)
and extract it to your `%appdata%\SpaceEngineers\Mods` folder
