### ISSUE TITLE
Typing a "P" in the name of a palette exits the color picker

### ISSUE THREAD

**Issue by Codebreakerblue** [SiskSjet/BuildColors#6]
Typing a letter "P" while inputting the name of a palette exits the color picker, leaving the input box on screen. Not a big problem, as pressing P again brings back the window without issue.
(Not sure if this is the right place to put this, if this a Rich HUD Master bug please let me know!)
![image](https://user-images.githubusercontent.com/18739767/232337263-17c3e5cb-64a0-4694-a8cf-5990e464b8c0.png)

**Comment by SiskSjet** [comment]
Yea, I know, but I'm not sure how to resolve it.
Normally, Rich HUD bypasses this issue by requiring the user to open the chat to input text, but it is not possible in the Color Picker screen.

**Comment by Codebreakerblue** [comment]
Oh I see. No problem! Awesome plugin by the way, the new GUI is stellar.

**Comment by QBFreak** [comment]
For completeness, there are similar issues with `i` and presumably `K`.

Anyone else that finds themselves here because of this issue: you can work around it by saving via command, `/bc save pinK is the best color`
